### ISSUE TITLE
Publish the ASTs and parsers for the ASTs for the FsLex and FsYacc tools to enable more robust editor tooling

### ISSUE THREAD

**Issue by baronfel** [fsprojects/FsLexYacc#143]
### Description

Currently, the ASTs and parsers for FsLex and FsYacc are internal to the tools themselves. It would be wonderful to have a published version of the AST structures and parsers for them, to enable me to improve FSAutoComplete (the LSP engine behind Ionide in VSCode) as well as other editors with better tooling around these files.

Having access to these structures would allow:

* better highlighting, navigation, find-references, and tooltips for these structures (imagine being able to CMD+Click on a rule name and go to its definition, for example),
* enable better integration with the F# portions of code in the rule productions, by allowing us to make virtual F# files whose contents are the contents of the 'top code' plus the contents of each rules' specific production,
* enable Web-based tooling via transpilation to fable (imagine something like the [fantomas tools](https://fsprojects.github.io/fantomas-tools/) but for FsLEx/FsYacc files)
* and any number of other scenarios that I'm not imaginative enough to express.

I propose that a new layer of library be added between each of fsyacc and fslex like so:

* FsLexYacc.Runtime -> FsLex.Core -> fslex
* FsLexYacc.Runtime -> FsYacc.Core -> fsyacc

such that most of the AST, parsers, and logic for each project are pushed down into the core layers, and the outer projects mainly orchestrate calling into this core logic.

**Comment by baronfel** [comment]
If this is approved, I'd be happy to contribute an MR for it.

**Comment by dsyme** [comment]
Approved

**Comment by baronfel** [comment]
The associated MR was merged, can a new release be done that includes the new packages?

**Comment by sergey-tihon** [comment]
I can help with publishing but I am not sure about dependencies ... They looks wrong

- It is OK tha there is no package that depend on `FsLexYacc.Runtime`?
- `FsLex.Core` depends on metapackage `FsLexYacc` ?
- `FsLexYacc ` has no dependencies? 

```yaml
Metadata:
  id: FsLex.Core
Dependencies:
  .NETStandard2.0:
    FSharp.Core: '>= 4.6.2'
    FsLexYacc: '>= 10.2.0'
```

```yaml
Metadata:
  id: FsYacc.Core
Dependencies:
  .NETStandard2.0:
    FSharp.Core: '>= 4.6.2'
```

```yaml
Metadata:
  id: FsLexYacc.Runtime
Dependencies:
  .NETStandard2.0:
    FSharp.Core: '>= 4.6.2'
```

```yaml
Metadata:
  id: FsLexYacc
Dependencies:
```
